# Use the latest foundry image
FROM ghcr.io/foundry-rs/foundry

# Copy our source code into the container
USER foundry
RUN mkdir -p /home/foundry/app
WORKDIR /home/foundry/app
COPY --chown=foundry:foundry ./ ./

# Build and test the source code
RUN forge test